tap "domt4/autoupdate"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "ack"
brew "openssl@1.1"
brew "readline"
brew "sqlite"
brew "xz"
brew "asciinema"
brew "brew-cask-completion"
brew "cmake"
brew "coreutils"
brew "openjdk"
brew "emscripten"
brew "exercism"
brew "git"
brew "htop"
brew "hugo"
brew "jq"
brew "mackup"
brew "mas"
brew "pyenv"
brew "sdl2"
brew "tldr"
brew "tmux"
brew "tree"
brew "vim"
brew "wget"
brew "zlib"
brew "zsh"
cask "anki"
cask "bitwarden"
cask "calibre"
cask "cheatsheet"
cask "clion"
cask "cyberduck"
cask "docker"
cask "firefox"
cask "iina"
cask "intellij-idea"
cask "iterm2"
cask "itsycal"
cask "kid3"
cask "kindle-previewer"
cask "krita"
cask "ledger-live"
cask "maccy"
cask "meld"
cask "monitorcontrol"
cask "omnidisksweeper"
cask "pycharm"
cask "qbittorrent"
cask "qlimagesize"
cask "qlprettypatch"
cask "qlvideo"
cask "quicklook-csv"
cask "quicklook-json"
cask "quicklookase"
cask "rectangle"
cask "steam"
cask "sublime-text"
cask "suspicious-package"
cask "syntax-highlight"
cask "visual-studio-code"
cask "webpquicklook"
cask "wireshark"
mas "Accelerate", id: 1459809092
mas "AdGuard for Safari", id: 1440147259
mas "Amphetamine", id: 937984704
mas "Honey", id: 1472777122
mas "iMazing HEIC Converter", id: 1292198261
mas "Messenger", id: 1480068668
mas "The Unarchiver", id: 425424353
mas "Tomato 2", id: 1494210770
mas "Tot", id: 1491071483
mas "WhatsApp", id: 1147396723
mas "Xcode", id: 497799835
