tap "arkweid/lefthook"
tap "homebrew/bundle"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
brew "xz"
brew "openssl@3"
brew "readline"
brew "asdf"
brew "bash"
brew "bash-completion"
brew "brew-cask-completion"
brew "cmake"
brew "cookiecutter"
brew "direnv"
brew "exiftool"
brew "ffmpeg"
brew "fzf"
brew "git"
brew "go"
brew "hadolint"
brew "htop"
brew "hugo"
brew "mackup"
brew "mas"
brew "node"
brew "openjdk"
brew "python@3.9"
brew "spek"
brew "tldr"
brew "tmux"
brew "zsh"
brew "arkweid/lefthook/lefthook"
cask "audacity"
cask "balenaetcher"
cask "betterzip"
cask "calibre"
cask "docker"
cask "firefox"
cask "ghostty"
cask "google-chrome"
cask "handbrake"
cask "iina"
cask "inkscape"
cask "insomnia"
cask "intellij-idea-ce"
cask "iterm2"
cask "jordanbaird-ice"
cask "kid3"
cask "kindle-previewer"
cask "logitech-unifying"
cask "mediahuman-audio-converter"
cask "monitorcontrol"
cask "omnidisksweeper"
cask "qbittorrent"
cask "rectangle"
cask "rekordbox"
cask "steam"
cask "stretchly"
cask "sublime-text"
cask "syntax-highlight"
cask "visual-studio-code"
cask "zoom"
mas "Accelerate", id: 1459809092
mas "AdGuard for Safari", id: 1440147259
mas "Amphetamine", id: 937984704
mas "Bitwarden", id: 1352778147
mas "Dark Reader for Safari", id: 1438243180
mas "DaVinci Resolve", id: 571213070
mas "Hover for Safari", id: 1540705431
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "PayPal Honey", id: 1472777122
mas "Right Click", id: 1364038646
mas "Shazam", id: 897118787
mas "Streaks", id: 963034692
mas "The Unarchiver", id: 425424353
mas "Tomato 2", id: 1494210770
mas "Xcode", id: 497799835
mas "‎WhatsApp", id: 310633997
vscode "christian-kohler.path-intellisense"
vscode "davidanson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "exiasr.hadolint"
vscode "foxundermoon.shell-format"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "golang.go"
vscode "mechatroner.rainbow-csv"
vscode "mikestead.dotenv"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "redhat.vscode-yaml"
vscode "rust-lang.rust-analyzer"
vscode "streetsidesoftware.code-spell-checker"
vscode "tamasfe.even-better-toml"
vscode "timonwong.shellcheck"
vscode "ue.alphabetical-sorter"
vscode "vadimcn.vscode-lldb"
vscode "viablelab.capitalize"
vscode "znck.grammarly"
